beetl:
  templates-path: templates
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8098
socket:
  pool-core: 10
  pool-keep: 20
  pool-max: 30
  pool-queue-init: 10
  port: 2323
spring:
  datasource:
    password: xwnbHyT6KM@t
    url: jdbc:mysql://localhost:3308/iotcloudtr?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: iotcloudtr
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      static-locations: classpath:/
